spring:
  application:
    name: api-gateway
server:
  port: 1101
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

zuul:
  routes:
    eureka-consumer:
      path: /eureka-consumer/**
      service-id: eureka-consumer
